DROP TABLE IF EXISTS EXCHANGE_RATE;

CREATE TABLE EXCHANGE_RATE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FROM_CURRENCY_TYPE VARCHAR(250) NOT NULL,
  TO_CURRENCY_TYPE VARCHAR(250) NOT NULL,
  PRICE DECIMAL(20,6) NOT NULL
);

INSERT INTO EXCHANGE_RATE (FROM_CURRENCY_TYPE, TO_CURRENCY_TYPE, PRICE)
VALUES
  ('PEN','USD', 3.51),
  ('USD','PEN', 0.28),
  ('PEN','EUR', 4.20),
  ('EUR','PEN', 0.24),
  ('PEN','CAD', 2.70),
  ('CAD','PEN', 0.37),
  ('USD','EUR', 1.23),
  ('EUR','USD', 0.85),
  ('USD','CAD', 0.76),
  ('CAD','USD', 1.32),
  ('EUR','CAD', 0.64),
  ('CAD','EUR', 1.55);